app/blog/routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask.json import jsonify
from flask_login import current_user, login_required

from app.apiauthhelper import token_required

from .forms import CreatePostForm, UpdatePostForm

from app.models import Post, Pokemon, Ability

# create instance of blueprint
blog = Blueprint('blog', __name__, template_folder='blog_templates')

from app.models import db

import requests as r
@blog.route('/')
def blogHome():
    posts = Post.query.all()
    return render_template('blog.html', posts = posts)

@blog.route('/pokebikes')
def pokeBikes():
    data = r.get('https://pokeapi.co/api/v2/item/bicycle/')
    my_data = data.json()
    bikes = [dict['name'] for dict in my_data['names']]
    my_img = my_data['sprites']['default']
    return render_template('pokebikes.html', bikes=bikes, my_img=my_img)

@blog.route('/blog/<int:id>')
def individualPost(id):
    post = Post.query.filter_by(id=id).first()
    if post is None:
        return redirect(url_for('blog.blogHome'))
    return render_template('individualpost.html', p = post)

@blog.route('/posts/delete/<int:id>', methods = ["POST"])
@login_required
def deletePost(id):
    post = Post.query.filter_by(id=id).first()
    if post.user_id != current_user.id:
        return redirect(url_for('blog.blogHome'))
    
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for('blog.blogHome'))

@blog.route('/posts/update/<int:id>', methods = ["GET","POST"])
@login_required
def updatePost(id):
    post = Post.query.filter_by(id=id).first()
    if post.user_id != current_user.id:
        return redirect(url_for('blog.blogHome'))


    form = UpdatePostForm()
    if request.method == "POST":
        if form.validate():
            
            title = form.title.data
            image = form.image.data
            content = form.content.data

            if not title:
                title = post.title
            if not image:
                image = post.image
            if not content:
                content = post.content

            # Updating the Post object
            post.title = title
            post.image = image
            post.content = content

            # commit to databse
            db.session.commit()

            return redirect(url_for('blog.individualPost', id=id))
    return render_template('updatepost.html', form = form)

@blog.route('/posts/create', methods = ["GET","POST"])
@login_required
def createPost():
    form = CreatePostForm()
    if request.method == "POST":
        if form.validate():
            
            title = form.title.data
            image = form.image.data
            content = form.content.data

            # create instance new post
            post = Post(title, image, content, current_user.id)
            # add instance to databse
            db.session.add(post)
            # commit to databse
            db.session.commit()

            return redirect(url_for('home'))
    return render_template('createpost.html', form = form)

@blog.route('/search/pokemon', methods = ['POST'])
def searchPokemon():
    
    if request.method == "POST":
        my_pokemon = request.form['poke']
        data = r.get(f'https://pokeapi.co/api/v2/pokemon/{my_pokemon}')
        if data.status_code == 200:
            my_data = data.json()

            pokemon = {
                'name': '',
                'image': '',
                'abilities': []
            }

            for ability in my_data['abilities']:
                pokemon['abilities'].append(ability['ability']['name'])
            pokemon['name'] = my_data['name']
            pokemon['image'] = my_data['sprites']['other']['dream_world']['front_default']
            id = my_data['id']

            my_pokemon = Pokemon.query.filter_by(id=id)
            if not my_pokemon:
            # instantiate Pokemon and Ability
                my_pokemon = Pokemon(id, pokemon['name'], pokemon['image'])
                db.session.add(my_pokemon)
                if len(pokemon['abilities']) == 2:
                    ability2 = Ability(pokemon['abilities'][1], id)
                    ability1 = Ability(pokemon['abilities'][0], id)
                    db.session.add(ability2)
                    db.session.add(ability1)
                elif len(pokemon['abilities']) == 1:
                    ability1 = Ability(pokemon['abilities'][1], id)
                    db.session.add(ability1)
                db.session.commit()
                

            # grab information and pass to a template.
            return render_template('pokemon.html', pokemon = pokemon)
        else:
            pokemon = ''
            return render_template('pokemon.html', pokemon = pokemon)
    return {'hi': 'there'}




@blog.route('/api/posts')
def apiBlogPosts():
    posts = Post.query.all()
    return jsonify([p.to_dict() for p in posts])

app/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1>This is the ABOUT page</h1>
{% endblock content %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
<title>{{ my_title }}</title>
</head>
<body>

    {% include 'nav.html' %}

      <main class="container main">
        {% with messages = get_flashed_messages(with_categories = True) %}
          {% if messages %}
          <div class="shoha-floats-down-here">

          
            {% for category, message in messages %}
            <div class="shoha-floats-down-here-child alert alert-{{ category }} alert-dismissible fade show mt-3" role="alert">
              <strong>{{ message }}</strong>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>

            {% endfor %}

          </div>
          {% endif %}
        {% endwith %}
        




          {% block content %}







          {% endblock content %}
      </main>

    {% include 'footer.html' %}




<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/footer.html
<footer>
    Author: Matias Nazabal <br>
    contact@matias-email.com
</footer>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1>This is my Bike Shop</h1>
<ul>
    {% for item in my_list  %}
        {% if item == "Shoha" %}
            <li><b>{{ item }}</b></li>
        {% else %}
            <li>{{ item }}</li>
        {% endif %}
    {% endfor %}
</ul>
{% endblock content %}

app/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Shoha's Bike Shop</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('shop.allProducts') }}">Shop</a>
                </li>
                <!-- <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li> -->


                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('blog.createPost') }}">Create Post</a>
                </li>
                <li class="nav-item">
                    <p class="nav-link" >Hello, {{ current_user.username }}</p>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logMeOut') }}">Log Out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{{ url_for('auth.logMeIn') }}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{{ url_for('auth.signMeUp') }}">Sign Up</a>
                </li>

                {% endif %}







            </ul>
            <form class="d-flex" action="/search/pokemon" method="POST">
                <input class="form-control me-2" type="input" name='poke' value='{{ request.form["poke"] }}' placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>